name: Terraform apply

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
    paths-ignore:
      - 'README.md'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
  AWS_ENDPOINT_URL: ${{ secrets.MINIO_ENDPOINT }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  terraform-apply:
    if: github.event.pull_request.merged == true
    name: Terraform apply
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read manifest file
        run: |
          echo 'manifest<<EOF' >> $GITHUB_ENV
          cat packer-manifest.json >> $GITHUB_ENV
          echo -e '\nEOF' >> $GITHUB_ENV

      - name: Extract BASE_VM_NAME
        run: |
          echo 'BASE_VM_NAME=${{ fromJSON(env.manifest).builds[0].custom_data.vm_name }} >> $GITHUB_ENV'

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1

      - name: Download Terraform plan from MinIO
        run: aws --no-verify-ssl s3 cp s3://${{ secrets.MINIO_BUCKET_NAME }}/pr-${{ env.PR_NUMBER }}.tfplan plan.tfplan

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Apply Terraform plan
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}
          TF_CLOUD_HOSTNAME: ${{ secrets.TF_CLOUD_HOSTNAME }}
          TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
          TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
          PM_API_URL: ${{ secrets.PM_API_URL }}
          PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
          PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
          TF_VAR_ssh_pub_key: ${{ vars.TF_VAR_SSH_PUB_KEY }}
          TF_VAR_master_count: ${{ vars.TF_VAR_MASTER_COUNT }}
          TF_VAR_worker_count: ${{ vars.TF_VAR_WORKER_COUNT }}
          TF_VAR_master_cores: ${{ vars.TF_VAR_MASTER_CORES }}
          TF_VAR_worker_cores: ${{ vars.TF_VAR_WORKER_CORES }}
          TF_VAR_master_memory: ${{ vars.TF_VAR_MASTER_MEMORY }}
          TF_VAR_worker_memory: ${{ vars.TF_VAR_WORKER_MEMORY }}
          TF_VAR_base_vm_name: ${{ env.BASE_VM_NAME }}
        run: |
          terraform init -upgrade
          terraform apply -auto-approve plan.tfplan

  cleanup:
    if: always()
    name: Cleanup after apply
    runs-on: self-hosted
    needs: terraform-apply
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1

      - name: Remove Terraform plan file from MinIO
        run: aws --no-verify-ssl s3 rm s3://${{ secrets.MINIO_BUCKET_NAME }}/pr-${{ env.PR_NUMBER }}.tfplan
