name: Terraform apply

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  fetch-last-pr:
    name: Fetch last merged PR
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.get_pr.outputs.PR_NUMBER }}
    steps:

      - name: Identify Last Merged PR
        id: get_pr
        run: |
          LAST_PR=$(gh pr list --state merged --limit 1 --json number --jq '.[0].number')
          echo "PR_NUMBER=$LAST_PR" >> $GITHUB_OUTPUT

  terraform-apply:
    name: Terraform apply
    runs-on: self-hosted
    needs: fetch-last-pr
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read manifest file
        run: |
          echo 'manifest<<EOF' >> $GITHUB_ENV
          cat packer-manifest.json >> $GITHUB_ENV
          echo -e '\nEOF' >> $GITHUB_ENV

      - name: Extract BASE_VM_NAME
        run: |
          echo 'BASE_VM_NAME=${{ fromJSON(env.manifest).builds[0].custom_data.vm_name }} >> $GITHUB_ENV'

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: "terraform-plan-${{ needs.fetch-last-pr.outputs.pr_number }}"
          path: .

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Apply Terraform plan
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}
          TF_CLOUD_HOSTNAME: ${{ secrets.TF_CLOUD_HOSTNAME }}
          TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
          TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
          PM_API_URL: ${{ secrets.PM_API_URL }}
          PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
          PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
          TF_VAR_ssh_pub_key: ${{ vars.TF_VAR_SSH_PUB_KEY }}
          TF_VAR_master_count: ${{ vars.TF_VAR_MASTER_COUNT }}
          TF_VAR_worker_count: ${{ vars.TF_VAR_WORKER_COUNT }}
          TF_VAR_master_cores: ${{ vars.TF_VAR_MASTER_CORES }}
          TF_VAR_worker_cores: ${{ vars.TF_VAR_WORKER_CORES }}
          TF_VAR_master_memory: ${{ vars.TF_VAR_MASTER_MEMORY }}
          TF_VAR_worker_memory: ${{ vars.TF_VAR_WORKER_MEMORY }}
        run: |
          terraform init -upgrade
          terraform apply -auto-approve plan.tfplan
