name: Terraform apply

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
    paths-ignore:
      - 'README.md'
      - 'renovate.json'
  workflow_dispatch:

jobs:
  download-from-min-io:
    name: Download Terraform plan and exitcode from MinIO
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      AWS_ENDPOINT_URL: ${{ secrets.MINIO_ENDPOINT }}
    runs-on: self-hosted
    container:
      image: amazon/aws-cli:latest
    if: github.event_name == 'pull_request_target' && github.event.pull_request.merged == true
    steps:
      - name: Download Terraform plan and exitcode from MinIO
        uses: ./.github/actions/s3-cp
        with:
          aws_access_key_id: ${{ secrets.MINIO_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.MINIO_SECRET_KEY }}
          aws_endpoint_url: ${{ secrets.MINIO_ENDPOINT }}
          source: |
            s3://${{ secrets.MINIO_TF_PLAN_BUCKET }}/pr-${{ github.event.pull_request.number }}/
          destination: .
          recursive: 'true'
          no_verify_ssl: 'true'

      - name: Upload Terraform plan and exitcode artifacts
        uses: actions/upload-artifact@v6
        with:
          name: tfplan
          path: |
            plan.tfplan
            plan.exitcode

  apply:
    name: Terraform apply
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    container:
      image: hashicorp/terraform:latest
    needs: download-from-min-io
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Read manifest file
        run: |
          echo 'manifest<<EOF' >> $GITHUB_ENV
          cat packer-manifest.json >> $GITHUB_ENV
          echo -e '\nEOF' >> $GITHUB_ENV

      - name: Download Terraform plan artifact
        if: github.event_name == 'pull_request_target'
        uses: actions/download-artifact@v7
        with:
          name: tfplan

      - name: Check for changes
        id: check
        run: |
          # Default to true for manual dispatch
          HAS_CHANGES="true"
          
          if [[ -f "plan.exitcode" ]]; then
            CODE=$(cat plan.exitcode)
            # Code 2 means changes present. Code 0 means no changes.
            if [[ "$CODE" == "2" ]]; then
              HAS_CHANGES="true"
              echo "⚠️ Changes detected (Exit Code 2)."
            else
              HAS_CHANGES="false"
              echo "✅ No changes (Exit Code $CODE)."
            fi
          fi
          
          echo "has_changes=$HAS_CHANGES" >> $GITHUB_OUTPUT

      - name: Apply Terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.MINIO_ENDPOINT }}
          PM_API_URL: ${{ secrets.PM_API_URL }}
          PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
          PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
          TF_VAR_ssh_pub_key: ${{ vars.TF_VAR_SSH_PUB_KEY }}
          TF_VAR_base_vm_name: ${{ fromJSON(env.manifest).builds[0].custom_data.vm_name }}
        run: |
          terraform init
          if [[ -f "plan.tfplan" ]]; then
            terraform apply plan.tfplan
          else
            terraform apply -auto-approve
          fi

      # - name: Trigger Ansible Deployment
      #   # Run if Apply Succeeded AND Changes were detected
      #   if: success() && steps.check.outputs.has_changes == 'true'
      #   uses: peter-evans/repository-dispatch@v4
      #   with:
      #     token: ${{ secrets.ORG_DISPATCH_TOKEN }}
      #     repository: Starktastic-Homelab/ansible
      #     event-type: infrastructure-changed

  cleanup:
    name: Cleanup after apply
    runs-on: self-hosted
    container:
      image: amazon/aws-cli:latest
    if: github.event_name == 'pull_request_target' && github.event.pull_request.merged == true && always()
    needs: apply
    steps:
      - name: Remove Terraform plan & exitcode files from MinIO
        run: aws --no-verify-ssl s3 rm s3://${{ secrets.MINIO_TF_PLAN_BUCKET }}/pr-${{ github.event.pull_request.number }} --recursive --quiet
