# This is not a workflow that should be used often (or at all)!
name: Terraform destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Terraform destroy
    runs-on: self-hosted
    container:
      image: hashicorp/terraform:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Read manifest file
        run: |
          echo 'manifest<<EOF' >> $GITHUB_ENV
          cat packer-manifest.json >> $GITHUB_ENV
          echo -e '\nEOF' >> $GITHUB_ENV

      - name: Destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT }}
          PM_API_URL: ${{ secrets.PM_API_URL }}
          PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
          PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
          TF_VAR_ssh_pub_key: ${{ vars.TF_VAR_SSH_PUB_KEY }}
          TF_VAR_base_vm_name: ${{ fromJSON(env.manifest).builds[0].custom_data.vm_name }}
        run: |
          terraform init
          terraform destroy -auto-approve
