name: Format Terraform Files

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'

jobs:
  format:
    name: Format Terraform files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.ORG_DISPATCH_TOKEN }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Run Terraform fmt command
        id: fmt
        run: |
          CHANGED_FILES=$(terraform fmt -recursive .)
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Commit & push formatting changes
        if: steps.fmt.outputs.changed_files != ''
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "[skip ci] style: terraform fmt"
          git push
