name: Format

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  format:
    name: Format Terraform, YAML and JSON files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.ORG_DISPATCH_TOKEN }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Run Terraform fmt command
        run: terraform fmt -recursive .

      - name: Prettier
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --write **/*.{yaml,yml,json}
          no_commit: true
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: "style: apply automatic formatting"
