name: Lint and validate Terraform template

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  contents: write

jobs:
  terraform-lint-validate:
    name: Terraform lint & validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Format Terraform files
        id: fmt
        run: |
          CHANGED_FILES=$(terraform fmt -recursive . 2>/dev/null)
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "Changed files: $CHANGED_FILES"

      - name: Commit & push formatting changes
        if: steps.fmt.outputs.changed_files != ''
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "style: terraform fmt"
          git push -f origin HEAD:"${{ github.head_ref || github.ref_name }}"

      - name: Validate Terraform template
        env:
          # Make sure that validate does not fail due to unset variables
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}
          TF_CLOUD_HOSTNAME: ${{ secrets.TF_CLOUD_HOSTNAME }}
          TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
          TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
          TF_VAR_base_vm_name: 'base_vm_name'
          TF_VAR_ssh_pub_key: 'ssh_pub_key'
          TF_VAR_master_count: 1
          TF_VAR_worker_count: 1
          TF_VAR_master_cores: 1
          TF_VAR_worker_cores: 1
          TF_VAR_master_memory: 1024
          TF_VAR_worker_memory: 1024
        run: |
          terraform init -upgrade
          terraform validate
