on:
  workflow_call:

jobs:
  comment-plan-output:
    name: Comment plan output
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Terraform plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform show plan
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}
          TF_CLOUD_HOSTNAME: ${{ secrets.TF_CLOUD_HOSTNAME }}
          TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
          TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
        run: |
          terraform init -upgrade
          plan=$(terraform show -no-color plan.tfplan).workflow_run
          echo 'PLAN<<EOF' >> $GITHUB_ENV
          echo "$plan" >> $GITHUB_ENV
          echo -e '\nEOF' >> $GITHUB_ENV

      - name: Comment on Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body '''
          ## Terraform Plan ðŸ“–
          <details>
          <summary>Click to expand</summary>

          ```HCL
          ${{ env.PLAN }}
          ```

          </details>

          *Pusher: @${{ github.actor }}, Action: `${{ github.event_name }}`*'''
