name: Validate and format Terraform template

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'renovate.json'

permissions:
  contents: write

env:
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}
  TF_CLOUD_HOSTNAME: ${{ secrets.TF_CLOUD_HOSTNAME }}
  TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
  TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
  PM_API_URL: ${{ secrets.PM_API_URL }}
  PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
  PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
  TF_VAR_ssh_pub_key: ${{ vars.TF_VAR_SSH_PUB_KEY }}
  TF_VAR_master_count: ${{ vars.TF_VAR_MASTER_COUNT }}
  TF_VAR_worker_count: ${{ vars.TF_VAR_WORKER_COUNT }}
  TF_VAR_master_cores: ${{ vars.TF_VAR_MASTER_CORES }}
  TF_VAR_worker_cores: ${{ vars.TF_VAR_WORKER_CORES }}
  TF_VAR_master_memory: ${{ vars.TF_VAR_MASTER_MEMORY }}
  TF_VAR_worker_memory: ${{ vars.TF_VAR_WORKER_MEMORY }}

jobs:
  validate:
    name: Validate Terraform template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Validate
        env:
          TF_VAR_base_vm_name: 'base_vm_name'
        run: |
          terraform init -upgrade
          terraform validate

  format:
    name: Format Terraform files
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Format Terraform files
        id: fmt
        run: |
          CHANGED_FILES=$(terraform fmt -recursive .)
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Commit & push formatting changes
        if: steps.fmt.outputs.changed_files != ''
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "style: terraform fmt"
          git push -f origin HEAD:"${{ github.head_ref || github.ref_name }}"

  plan:
    name: Terraform plan
    runs-on: self-hosted
    needs: validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read manifest file
        run: |
          echo 'manifest<<EOF' >> $GITHUB_ENV
          cat packer-manifest.json >> $GITHUB_ENV
          echo -e '\nEOF' >> $GITHUB_ENV

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Create Terraform plan file
        env:
          TF_VAR_base_vm_name: ${{ fromJSON(env.manifest).builds[0].custom_data.vm_name }}
        run: |
          terraform init -upgrade
          terraform plan -out='plan.tfplan'
      
      - name: Upload Terraform plan to MinIO
        uses: ./github/actions/s3-cp
        with:
          aws_access_key_id: ${{ secrets.MINIO_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.MINIO_SECRET_KEY }}
          aws_endpoint_url: ${{ secrets.MINIO_ENDPOINT }}
          source: plan.tfplan
          destination: s3://${{ secrets.MINIO_BUCKET_NAME }}/pr-${{ github.event.pull_request.number }}.tfplan

      - name: Upload Terraform plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: plan.tfplan

  comment:
    name: Comment plan in Pull Request
    runs-on: ubuntu-latest
    needs: plan
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Terraform plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform show plan
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}
          TF_CLOUD_HOSTNAME: ${{ secrets.TF_CLOUD_HOSTNAME }}
          TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
          TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
        run: |
          terraform init -upgrade
          echo 'PLAN<<EOF' >> $GITHUB_ENV
          terraform show -no-color plan.tfplan >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Comment on Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body '''
          ## Terraform Plan ðŸ“–
          <details>
          <summary>Click to expand</summary>

          ```HCL
          ${{ env.PLAN }}
          ```

          </details>

          *Pusher: @${{ github.actor }}, Action: `${{ github.event_name }}`*'''
