name: Validate and format Terraform template

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'renovate.json'

permissions:
  contents: write

jobs:
  validate:
    name: Validate Terraform template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Validate
        env:
          # Make sure that validate does not fail due to unset variables
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}
          TF_CLOUD_HOSTNAME: ${{ secrets.TF_CLOUD_HOSTNAME }}
          TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
          TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
          PM_API_URL: 'https://proxmox.example.com:8006/api2/json'
          PM_API_TOKEN_ID: 'id'
          PM_API_TOKEN_SECRET: 'secret'
          TF_VAR_base_vm_name: 'base_vm_name'
          TF_VAR_ssh_pub_key: 'ssh_pub_key'
          TF_VAR_master_count: 1
          TF_VAR_worker_count: 1
          TF_VAR_master_cores: 1
          TF_VAR_worker_cores: 1
          TF_VAR_master_memory: 1024
          TF_VAR_worker_memory: 1024
        run: |
          terraform init -upgrade
          terraform validate

  format:
    name: Format Terraform files
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Format Terraform files
        id: fmt
        run: |
          CHANGED_FILES=$(terraform fmt -recursive .)
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Commit & push formatting changes
        if: steps.fmt.outputs.changed_files != ''
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "style: terraform fmt"
          git push -f origin HEAD:"${{ github.head_ref || github.ref_name }}"
