name: Validate and plan Terraform template

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'renovate.json'

env:
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}
  TF_CLOUD_HOSTNAME: ${{ secrets.TF_CLOUD_HOSTNAME }}
  TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
  TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
  PM_API_URL: ${{ secrets.PM_API_URL }}
  PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
  PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
  TF_VAR_ssh_pub_key: ${{ vars.TF_VAR_SSH_PUB_KEY }}

jobs:
  validate:
    name: Validate Terraform template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Validate
        env:
          TF_VAR_base_vm_name: 'base_vm_name'
        run: |
          terraform init
          terraform validate

  plan:
    name: Terraform plan
    runs-on: self-hosted
    needs: validate
    container:
      image: hashicorp/terraform:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Read manifest file
        run: |
          echo 'manifest<<EOF' >> $GITHUB_ENV
          cat packer-manifest.json >> $GITHUB_ENV
          echo -e '\nEOF' >> $GITHUB_ENV

      - name: Create Terraform plan file
        env:
          TF_VAR_base_vm_name: ${{ fromJSON(env.manifest).builds[0].custom_data.vm_name }}
        run: |
          terraform init

          set +e
          terraform plan -detailed-exitcode -out='plan.tfplan'
          EXIT_CODE=$?
          set -e

          echo "$EXIT_CODE" > plan.exitcode

          if [ $EXIT_CODE -eq 1 ]; then
            echo "‚ùå Terraform Plan failed with error."
            exit 1
          fi
          
          echo "‚úÖ Plan generated with Exit Code: $EXIT_CODE"

      - name: Upload Terraform plan artifact
        uses: actions/upload-artifact@v6
        with:
          name: tfplan
          path: plan.tfplan

      - name: Upload Terraform exitcode artifact
        uses: actions/upload-artifact@v6
        with:
          name: exitcode
          path: plan.exitcode

  upload-to-min-io:
    name: Upload Terraform plan and exitcode to MinIO
    runs-on: self-hosted
    needs: plan
    container:
      image: amazon/aws-cli:latest
    steps:
      - name: Download Terraform plan artifact
        uses: actions/download-artifact@v7
        with:
          name: tfplan
          path: plan.tfplan
      
      - name: Download Terraform exitcode artifact
        uses: actions/download-artifact@v7
        with:
          name: exitcode
          path: plan.exitcode

      - name: Upload Terraform plan to MinIO
        uses: ./.github/actions/s3-cp
        with:
          aws_access_key_id: ${{ secrets.MINIO_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.MINIO_SECRET_KEY }}
          aws_endpoint_url: ${{ secrets.MINIO_ENDPOINT }}
          source: plan.tfplan
          destination: s3://${{ secrets.MINIO_TF_PLAN_BUCKET }}/pr-${{ github.event.pull_request.number }}.tfplan

      - name: Upload ExitCode to MinIO
        uses: ./.github/actions/s3-cp
        with:
          aws_access_key_id: ${{ secrets.MINIO_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.MINIO_SECRET_KEY }}
          aws_endpoint_url: ${{ secrets.MINIO_ENDPOINT }}
          source: plan.exitcode
          destination: s3://${{ secrets.MINIO_TF_PLAN_BUCKET }}/pr-${{ github.event.pull_request.number }}.exitcode

  comment:
    name: Comment plan in Pull Request
    runs-on: ubuntu-latest
    needs: plan
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Restore Terraform plan artifact
        uses: actions/download-artifact@v7
        with:
          name: tfplan

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform show plan
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}
          TF_CLOUD_HOSTNAME: ${{ secrets.TF_CLOUD_HOSTNAME }}
          TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
          TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
        run: |
          terraform init
          echo 'PLAN<<EOF' >> $GITHUB_ENV
          terraform show -no-color plan.tfplan >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Comment on Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body '''
          ## Terraform Plan üìñ
          <details>
          <summary>Click to expand</summary>

          ```HCL
          ${{ env.PLAN }}
          ```

          </details>

          *Pusher: @${{ github.actor }}, Action: `${{ github.event_name }}`*'''
