name: Validate and plan Terraform template

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'renovate.json'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
  AWS_ENDPOINT_URL: ${{ secrets.MINIO_ENDPOINT }}
  MINIO_TF_PLAN_BUCKET: ${{ secrets.MINIO_TF_PLAN_BUCKET }}
  PM_API_URL: ${{ secrets.PM_API_URL }}
  PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
  PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
  TF_VAR_ssh_pub_key: ${{ vars.TF_VAR_SSH_PUB_KEY }}

jobs:
  validate-and-plan:
    name: Terraform plan
    runs-on: self-hosted
    container:
      image: hashicorp/terraform:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Validate Terraform template
        env:
          TF_VAR_base_vm_name: 'base_vm_name'
        run: |
          terraform init
          terraform validate

      - name: Read manifest file
        run: |
          echo 'manifest<<EOF' >> $GITHUB_ENV
          cat packer-manifest.json >> $GITHUB_ENV
          echo -e '\nEOF' >> $GITHUB_ENV

      - name: Create Terraform plan file
        env:
          TF_VAR_base_vm_name: ${{ fromJSON(env.manifest).builds[0].custom_data.vm_name }}
        run: |
          set +e
          terraform plan -no-color -detailed-exitcode -out='plan.tfplan' > plan.log
          EXIT_CODE=$?
          set -e

          cat plan.log

          echo "$EXIT_CODE" > plan.exitcode
          base64 plan.log > plan.log.b64

          if [ $EXIT_CODE -eq 1 ]; then
            echo "âŒ Terraform Plan failed with error."
            exit 1
          fi
          
          echo "âœ… Plan generated with Exit Code: $EXIT_CODE"

      - name: Upload Terraform plan artifact
        uses: actions/upload-artifact@v6
        with:
          name: tfplan
          path: |
            - plan.tfplan
            - plan.exitcode

      - name: Upload plan log artifact
        uses: actions/upload-artifact@v6
        with:
          name: planlog
          path: plan.log.b64

  upload-to-min-io:
    name: Upload Terraform plan and exitcode to MinIO
    runs-on: self-hosted
    needs: validate-and-plan
    container:
      image: amazon/aws-cli:latest
    steps:
      - name: Download Terraform plan artifact
        uses: actions/download-artifact@v7
        with:
          name: tfplan

      - name: Upload Terraform plan to MinIO
        uses: ./.github/actions/s3-cp
        with:
          aws_access_key_id: ${{ env.MINIO_ACCESS_KEY }}
          aws_secret_access_key: ${{ env.MINIO_SECRET_KEY }}
          aws_endpoint_url: ${{ env.MINIO_ENDPOINT }}
          source: plan.tfplan
          destination: s3://${{ env.MINIO_TF_PLAN_BUCKET }}/pr-${{ github.event.pull_request.number }}.tfplan
      - name: Upload ExitCode to MinIO
        uses: ./.github/actions/s3-cp
        with:
          aws_access_key_id: ${{ env.MINIO_ACCESS_KEY }}
          aws_secret_access_key: ${{ env.MINIO_SECRET_KEY }}
          aws_endpoint_url: ${{ env.MINIO_ENDPOINT }}
          source: plan.exitcode
          destination: s3://${{ env.MINIO_TF_PLAN_BUCKET }}/pr-${{ github.event.pull_request.number }}.exitcode
  comment:
    name: Comment plan in Pull Request
    runs-on: ubuntu-latest
    needs: validate-and-plan
    permissions:
      pull-requests: write
    steps:
      - name: Download Terraform plan log artifact
        uses: actions/download-artifact@v7
        with:
          name: planlog

      - name: Terraform decode plan log
        run: |
          base64 -d plan.log.b64 > plan.log
          PLAN=$(cat plan.log)
          echo "PLAN<<EOF" >> $GITHUB_ENV
          echo "$PLAN" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment on Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body '''
          ## Terraform Plan ðŸ“–
          <details>
          <summary>Click to expand</summary>

          ```HCL
          ${{ env.PLAN }}
          ```

          </details>

          *Pusher: @${{ github.actor }}, Action: `${{ github.event_name }}`*'''
